[PPD-171] change organization call
pagopa/pagopa-debt-position pull request #104
Opened 2022-05-27 13:17 UTC by alessio-acitelli

#### List of Changes

- added apiconfig call to check organization

#### Motivation and Context

- the call for organization check made on apiconfig guarantees better performance and more reliable verification

#### How Has This Been Tested?

Junit and Postaman test

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-27 14:56 UTC, alessio-acitelli commented
Il task PPD-171 ha impatti su due applicativi:

- payments
- gpd

Quale label utilizzo?

2022-05-30 10:09 UTC, jacopocarlini requested changes

2022-05-30 10:09 UTC, jacopocarlini commented on payments/src/main/java/it/gov/pagopa/payments/service/ApiConfigClient.java
> +    @Cacheable(value = "payment-options")
use a relevant value

2022-05-30 10:09 UTC, jacopocarlini commented on payments/src/test/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidatorTest.java
> +		// se arrivo qui la chiamata è andata a buon fine
use english

2022-05-30 10:29 UTC, jacopocarlini approved these changes
Good 🔝

2022-05-30 12:29 UTC, merged