fix: fixing regexp on country input PAGOPA-817
pagopa/pagopa-debt-position pull request #132
Opened 2023-03-22 15:33 UTC by FedericoRuzzier

#### List of Changes
Adding a regexp filter on the country input to respect the xml constraint (https://github.com/pagopa/pagopa-api/blob/c14593647793323f1941d2712acbf817e2cfb056/xsd-common/sac-common-types-1.0.xsd#L36)

#### Motivation and Context
These changes were needed in order not to upload debt position which could not be processed by the payments system

#### How Has This Been Tested?
This has been tested manually and with unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-03-23 08:16 UTC, pasqualespica requested changes

2023-03-23 08:16 UTC, pasqualespica commented on payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/DebtorModel.java
> +    @Pattern(regexp="[A-Z]{2}", message="The country must be reported with two capital letters (example: IT)")
remove `payments` folder according to https://github.com/pagopa/pagopa-gpd-payments too

2023-03-23 08:16 UTC, pasqualespica commented on payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/PaymentPositionModel.java
> +import javax.validation.constraints.Pattern;
ditto

2023-03-23 09:49 UTC, pasqualespica approved these changes

2023-03-24 10:05 UTC, andrea-deri approved these changes
Very nice! 👍🏻

2023-03-24 10:07 UTC, merged