[PPD-114] retry reporting service
pagopa/pagopa-debt-position pull request #75
Opened 2022-04-06 08:57 UTC by jacopocarlini

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-04-07 09:42 UTC, pasqualespica requested changes

2022-04-07 09:42 UTC, pasqualespica commented on reporting-service/src/main/java/it/gov/pagopa/reporting/functions/UpdateOption.java
> +import java.util.UUID;
remove

2022-04-07 09:42 UTC, pasqualespica commented on reporting-service/src/main/java/it/gov/pagopa/reporting/service/GPDService.java
> +        for (int i = 1; i <= maxAttemptsValue; i++) {
enqueue newly the message
As made for https://github.com/pagopa/pagopa-debt-position/blob/43dff4fc8134f574a68028d75213cbf4c8d657a7/reporting-batch/src/main/java/it/gov/pagopa/reporting/RetrieveFlows.java#L72

2022-04-08 14:10 UTC, jacopocarlini commented on reporting-service/src/main/java/it/gov/pagopa/reporting/functions/UpdateOption.java
> +import java.util.UUID;
done

2022-04-12 15:35 UTC, pasqualespica approved these changes
great 💪

2022-04-19 14:01 UTC, merged